[
    {
        "id": "3030",
        "blog_id": "0",
        "title": "無料アプリ「まいにちのいぬ・ねこのきもち」が大リニューアル！愛犬愛猫の写真投稿コーナーが登場♪（2016.08.26）",
        "body": "無料アプリ「まいにちのいぬ・ねこのきもち」が大リニューアル！愛犬愛猫の写真投稿コーナーが登場♪（2016.08.26）",
        "category": "注目の情報",
        "image_path": "https://inuneko-media.s3.amazonaws.com/campaign/fabb594ad064491b3e037ab3ab442dca.png",
        "url": "http://pet.benesse.ne.jp/topics/topic14_20160825.html",
        "seen_type": "0",
        "highlight_flag": "1",
        "blog_campaign_type": "1",
        "type": "1",
        "new": "0",
        "shop_id": "0"
    },
    {
        "id": "3031",
        "blog_id": "0",
        "title": "「いぬねこパーク」に投稿すると、愛犬愛猫の写真がふろくのカレンダーに掲載されるチャンス★リニューアル記念でプレゼントキャンペーンも実施中！",
        "body": "「いぬねこパーク」に投稿すると、愛犬愛猫の写真がふろくのカレンダーに掲載されるチャンス★リニューアル記念でプレゼントキャンペーンも実施中！",
        "category": "注目の情報",
        "image_path": "https://inuneko-media.s3.amazonaws.com/campaign/b1d2c1603003bfa9a3d41d19b51498d1.png",
        "url": "http://pet.benesse.ne.jp/topics/topic14_20160825_calendar.html",
        "seen_type": "0",
        "highlight_flag": "1",
        "blog_campaign_type": "1",
        "type": "1",
        "new": "0",
        "shop_id": "0"
    },
    {
        "id": "2998",
        "blog_id": "0",
        "title": "いぬのきもち＆カインズコラボ企画実施中！",
        "body": "いぬのきもちグッズふろく“ル・クルーゼお散歩ボウル”持ってカインズ行こ♪",
        "category": "お知らせ",
        "image_path": "https://inuneko-media.s3.amazonaws.com/campaign/9b1187576e69624fba94d981089bc05f.png",
        "url": "http://inuneko.me/hoken/cainz/index.html",
        "seen_type": "0",
        "highlight_flag": "1",
        "blog_campaign_type": "1",
        "type": "1",
        "new": "0",
        "shop_id": "0"
    },
    {
        "id": "2018",
        "blog_id": "0",
        "title": "毎日更新！話題の猫漫画『ペン太のこと』",
        "body": "笑い時々涙。猫と人がつむぐ家族の物語。",
        "category": "ピックアップ",
        "image_path": "https://inuneko-media.s3.amazonaws.com/api/data/2015/09/25/1095.jpg",
        "url": "http://www.moae.jp/comic/pentanokoto",
        "seen_type": "2",
        "highlight_flag": "0",
        "blog_campaign_type": "1",
        "type": "1",
        "new": "0",
        "shop_id": "0"
    },
    {
        "id": "2992",
        "blog_id": "0",
        "title": "お留守番中に愛犬がいい子にしているか心配で…。",
        "body": "外出先からペットの行動をスマホでチェック！いつでもどこでも留守番ケアを！",
        "category": "PR",
        "image_path": "https://inuneko-media.s3.amazonaws.com/campaign/e3057b1d76114950cc7bdb42f12fba66.png",
        "url": "http://r.ca-mpr.jp/s/93/?i4a=202369",
        "seen_type": "0",
        "highlight_flag": "0",
        "blog_campaign_type": "1",
        "type": "1",
        "new": "0",
        "shop_id": "0"
    },
    {
        "title": "猫好き必見！　魅惑の“ニャンポーズ”８連発！！",
        "body": "『ねこのきもち』2016年9月号「魅惑のニャンポーズ20」特集では、猫好きならわかる用語“ニャン語”を、読者のとっておきの愛猫写真とともに紹介しています。この中から一部をお見せしちゃいます！",
        "id": "u14v9600000087h8",
        "category": "もっと！ねこのきもち! | 特別企画",
        "image_path": "http://inuneko.me/topics/cat/u14v9600000087h8-img/u14v9600000087j5_thum.jpg",
        "url": "http://inuneko.me/topics/cat/topicc1_cat201609_pose.html",
        "seen_type": "0",
        "highlight_flag": "0",
        "type": "2",
        "blog_campaign_type": "1",
        "blog_id": "0",
        "shop_id": "0",
        "new": "1"
    },
    {
        "title": "いぬのきもち編集室便り　『名犬ティンクさんの話』",
        "body": "『いぬのきもち』編集室のメンバーが交代でお届けする「編集室便り」。今回は担当Mが「いぬのきもち」に欠かせない名犬・ティンクさんについて語ります！",
        "id": "u14v960000008a2u",
        "category": "もっと！いぬのきもち! | 特別企画",
        "image_path": "http://inuneko.me/topics/dog/u14v960000008a2u-img/9F9A6789_thum.jpg",
        "url": "http://inuneko.me/topics/dog/topicc1_dog_eye66.html",
        "seen_type": "0",
        "highlight_flag": "0",
        "type": "2",
        "blog_campaign_type": "1",
        "blog_id": "0",
        "shop_id": "0",
        "new": "1"
    },
    {
        "title": "無料アプリ「まいにちのいぬ・ねこのきもち」が大リニューアル！愛犬愛猫の写真投稿コーナーが登場♪（2016.08.26）",
        "body": "約100万人が利用している無料アプリ「まいにちのいぬ・ねこのきもち」が大リニューアル！毎日の犬猫動画や可愛い犬猫の画像がたくさん見られるいぬねこパークの登場です",
        "id": "u14v960000008e1e",
        "category": "いぬのきもち　ねこのきもちTOPICS | アプリ",
        "image_path": "http://inuneko.me/topics/u14v960000008e1e-img/u14v960000008e3f_thum.png",
        "url": "http://inuneko.me/topics/topic14_20160825.html",
        "seen_type": "0",
        "highlight_flag": "0",
        "type": "2",
        "blog_campaign_type": "1",
        "blog_id": "0",
        "shop_id": "0",
        "new": "1"
    },
    {
        "title": "ちょっとしたご褒美、お誕生日のお祝いや記念日に♪",
        "body": "犬も食べられる記念日用のスイーツで、大切な愛犬を喜ばせよう！",
        "id": "g6n2u90000013b4e",
        "category": "いぬのきもち ねこのきもち Web情報局 | おすすめ",
        "image_path": "http://inuneko.me/ranking/g6n2u90000013b4e-img/g6n2u90000013b5p_thum.jpg",
        "url": "http://inuneko.me/ranking/comif_1.html",
        "seen_type": "0",
        "highlight_flag": "0",
        "type": "2",
        "blog_campaign_type": "1",
        "blog_id": "0",
        "shop_id": "0",
        "new": "1"
    },
    {
        "title": "猫漫画家うだまさんの愛猫がねこのきもち９月号ふろく「ルドルフの旅する段ボールトラック」をお試し！さて、猫の反応は？",
        "body": "『ねこのきもち』2016年９月号連動のふろく「ルドルフの旅する段ボールトラック」を、猫漫画家うだまさんの愛猫に試していただきました。さて、猫の反応は？",
        "id": "u14v9600000081de",
        "category": "もっと！ねこのきもち! | 特別企画",
        "image_path": "http://inuneko.me/topics/cat/u14v9600000081de-img/u14v9600000081gh_thum.jpg",
        "url": "http://inuneko.me/topics/cat/topic1_cat_furoku201609_udama.html",
        "seen_type": "0",
        "highlight_flag": "0",
        "type": "2",
        "blog_campaign_type": "1",
        "blog_id": "0",
        "shop_id": "0",
        "new": "1"
    },
    {
        "title": "こむぎちゃんがいぬのきもち９月号ふろく「ル・クルーゼ お散歩用ボウル」を体験！",
        "body": "『いぬのきもち』2016年９月号のふろくは、「ル・クルーゼ お散歩用ボウル」。こむぎとのコミュニケーションで、さっそく使ってみました！",
        "id": "u14v96000000860j",
        "category": "もっと！いぬのきもち! | 特別企画",
        "image_path": "http://inuneko.me/topics/dog/u14v96000000860j-img/u14v96000000862q_thum.jpg",
        "url": "http://inuneko.me/topics/dog/topicc1_dog_furoku201609_02.html",
        "seen_type": "0",
        "highlight_flag": "0",
        "type": "2",
        "blog_campaign_type": "1",
        "blog_id": "0",
        "shop_id": "0",
        "new": "1"
    },
    {
        "title": "崩壊顔!?　セツがねこのきもち9月号ふろく「ルドルフの旅する段ボールトラック」を体験",
        "body": "崩壊顔!?　セツがねこのきもち9月号ふろく「ルドルフの旅する段ボールトラック」を体験",
        "id": "u14v960000008gqe",
        "category": "もっと！ねこのきもち! | 特別企画",
        "image_path": "http://inuneko.me/topics/cat/u14v960000008gqe-img/u14v960000008gsh_thum.jpg",
        "url": "http://inuneko.me/topics/cat/topic14_cat_furoku201609_setu.html",
        "seen_type": "0",
        "highlight_flag": "0",
        "type": "2",
        "blog_campaign_type": "1",
        "blog_id": "0",
        "shop_id": "0",
        "new": "1"
    },
    {
        "title": "「いぬねこパーク」に投稿すると、愛犬愛猫の写真がふろくのカレンダーに！？プレゼントキャンペーンも実施中★",
        "body": "「いぬねこパーク」に投稿すると、愛犬愛猫の写真がふろくのカレンダーに掲載されるチャンス★無料アプリ「まいにちのいぬ・ねこのきもち」リニューアル記念でプレゼントキャンペーンも実施中！",
        "id": "u14v960000008gg6",
        "category": "いぬのきもち　ねこのきもちTOPICS | アプリ",
        "image_path": "http://inuneko.me/topics/u14v960000008gg6-img/u14v960000008gi1_thum.png",
        "url": "http://inuneko.me/topics/topic14_20160825_calendar.html",
        "seen_type": "0",
        "highlight_flag": "0",
        "type": "2",
        "blog_campaign_type": "1",
        "blog_id": "0",
        "shop_id": "0",
        "new": "1"
    },
    {
        "title": "新入り・ヨミと、伝説の男・セツ",
        "body": "新入り・ヨミと、伝説の男・セツ新入りヨミィの暴虐（ぼうぎゃく）は今日も絶好調です。\tものを壊し、走りまわり、疲れたら近くの猫にパンチ、人間が抱き上げようとすると、積極的によじ登ってきて鼻の頭に噛み付き１発。\tすべてゴロゴロいいながら行うのが一層恐ろしい。ご機嫌だよこのコ！本日は、攻めまくってるフレッシュな新入りの、先住猫との関係性についてお話したいと思います。我が家に来てはや1カ月。傍若無人（ぼう",
        "id": "g6n2u90000013lfp",
        "category": "残念なイケメン猫　揺るぎなきセツSTYLE | コラム",
        "image_path": "http://inuneko.me/setsu/g6n2u90000013lfp-img/g6n2u90000013lh2_thum.jpg",
        "url": "http://inuneko.me/setsu/setsu_vol78.html",
        "seen_type": "0",
        "highlight_flag": "0",
        "type": "2",
        "blog_campaign_type": "1",
        "blog_id": "0",
        "shop_id": "0",
        "new": "1"
    },
    {
        "title": "小悪魔こむぎ、ふなっしーに会う",
        "body": "小悪魔こむぎ、ふなっしーに会うかわいい顔でまわりを振り回しちゃう小さな柴の小悪魔犬『こむぎ』です。今回は、ふなっしーカレンダーの撮影にこむぎが参加したときのお話です。カレンダー撮影にまさかのオファー！以前、いぬのきもち2016年３月号のふろく「ふなっしーロープおもちゃ」の体験記事を書いたときにも話しましたが、わたくし（こむぎ母：きよ）はふなっしーのファンです。\tそんな私にとって夢のような話が舞い込",
        "id": "g6n2u90000013lmr",
        "category": "柴犬こむぎの小悪魔日記 | コラム",
        "image_path": "http://inuneko.me/komugi/g6n2u90000013lmr-img/g6n2u90000013lo4_thum.jpg",
        "url": "http://inuneko.me/komugi/komugi_vol95.html",
        "seen_type": "0",
        "highlight_flag": "0",
        "type": "2",
        "blog_campaign_type": "1",
        "blog_id": "0",
        "shop_id": "0",
        "new": "1"
    }
]
